apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-service-management
spec:
  template:
    metadata:
      labels:
        app: sample-service-management
    spec:
      containers:
      - name: sample-service-management
        image: mesfcontainerregistry.azurecr.io/test-image:19
      ports:
      - port: 8080
        name: http
      selector:
        app: sample-service-management
      type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service-management
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: sample-service-management