FROM microsoft/aspnetcore-build:2.0
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["samples/SampleServiceManagement.AspNetCore/SampleServiceManagement.AspNetCore.csproj", "samples/SampleServiceManagement.AspNetCore/"]
COPY ["src/MESF.Core.ServiceManagement/MESF.Core.ServiceManagement.csproj", "src/MESF.Core.ServiceManagement/"]

RUN dotnet restore "samples/SampleServiceManagement.AspNetCore/SampleServiceManagement.AspNetCore.csproj"
COPY . .
WORKDIR "/src/samples/SampleServiceManagement.AspNetCore"
RUN dotnet build --no-restore "SampleServiceManagement.AspNetCore.csproj" -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]