version: '3.4'

services:
  sampleservicemanagement.aspnetcore:
    image: ${DOCKER_REGISTRY}sampleservicemanagementaspnetcore
    build:
      context: .
      dockerfile: samples/SampleServiceManagement.AspNetCore/Dockerfile

    depends_on:
    - rabbitmq
    - sql.data

  rabbitmq:
    image: rabbitmq:3-management

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

#  nosql.data:
#    image: mongo
#networks:
#  default:
#    external:
#      name: nat