version: '3.4'

services:
  sampleservicemanagement.aspnetcore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
