version: '3.4'

services:
  sampleservicemanagement.aspnetcore:
    image: ${DOCKER_REGISTRY}sampleservicemanagementaspnetcore
    build:
      context: .
      dockerfile: samples/SampleServiceManagement.AspNetCore/Dockerfile

    depends_on:
    - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
